### ISSUE TITLE
ScriptSQL automatico

### ISSUE THREAD

**Issue by danidiazd** [invictuzzzzz/FlowerStore#23]
Creado en la rama feature/scripts . He expandido el properties y he recogido la información del scriptSQL para que lo lea y lo pase de vuelta. Cambiando el nombre "nombre a cambiar" por el que pase por parametro.
Se llama desde demo y deberia ir, pero no funciona.

**Comment by invictuzzzzz** [comment]
Creado en la rama feature/scripts . He expandido el properties y he recogido la información del scriptSQL para que lo lea y lo pase de vuelta. Cambiando el nombre "nombre a cambiar" por el que pase por parametro. 
Se llama desde demo y deberia ir, pero no funciona.
